### ISSUE TITLE
Publish generated docset somewhere

### ISSUE THREAD

**Issue by haad** [Smolations/more-dash-docsets#3]
generated docsets should be published somewhere

**Comment by Kapeli** [comment]
https://github.com/Kapeli/Dash-User-Contributions#contribute-a-new-docset

**Comment by Smolations** [comment]
Haha yup, this repo was created long before there was an easy (or really, _any_) way to submit user-generated docsets. I can probably kill this project and submit any docsets to the official URL provided. Thanks for the reminder folks!
